#!/usr/bin/env python3
from shutil import which
from typing import List, Tuple
from subprocess import PIPE, run

import argparse
import json
import toml
import sys
import os
import itertools

VERSION = "0.1.0"
PROG = sys.argv[0]
DEPS = [
    "stemp",
    "frontmatter",
    "pandoc",
]

version_text = f"""{PROG} {VERSION}

Source Code: https://github.com/rythoris/static
Bug Tracker: https://github.com/rythoris/static/issues
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog=PROG)
    sub_parser = parser.add_subparsers(title="sub-commands", dest="cmd")

    parser.add_argument("-v", "--version", action="version", version=version_text)
    parser.add_argument("-i", "--include", action="append", default=[],
                        help="include the file to the final template params."
                        "included files will be available under the name of the"
                        "file without the '.json' extension")
    parser.add_argument("-t", "--include-template", action="append", dest="includes", default=[],
                        help="pass these templates to the stemp -i, --include flag.")

    single_parser = sub_parser.add_parser('single')
    single_parser.add_argument("-o", "--output",
                               help="Output file. by default it will execute the"
                               "template and print the result to to the stdout.")
    single_parser.add_argument("template", metavar="TEMPLATE")
    single_parser.add_argument("input_file", metavar="INPUT_FILE")

    list_parser = sub_parser.add_parser('list')
    list_parser.add_argument("-s", "--summary-length", type=int, default=50)
    list_parser.add_argument("-o", "--output",
                             help="Output file. by default it will execute the"
                             "template and print the result to to the stdout.")
    list_parser.add_argument("template", metavar="TEMPLATE")
    list_parser.add_argument("files", nargs='+', metavar="FILES")

    return parser.parse_args()


def markdown_to_html(markdown_content: str) -> str:
    return run(
        ("pandoc", "--from", "gfm", "--to", "html", "-"),
        encoding="utf-8",
        input=markdown_content,
        stdout=PIPE,
        check=True
    ).stdout


def load_vars_file(filepath: str) -> dict:
    with open(filepath, "r") as f:
        match os.path.splitext(filepath)[1].removeprefix("."):
            case "json": return json.loads(f.read())
            case "toml": return toml.loads(f.read())
            case _:
                print(f"{PROG}: error: could not detect the vars file format based on extension: {filepath}", file=sys.stderr)
                exit(1)


def include_files(files: List[str]) -> dict:
    res = {}
    for file in files:
        file_ext = os.path.splitext(file)[1]
        file_name = os.path.basename(file)
        try:
            res[file_name.removesuffix(file_ext)] = load_vars_file(file)
        except Exception as err:
            print(f"{PROG}: error: could not include file: {file}: {err}", file=sys.stderr)
            exit(1)
    return res


def gen_summary(content: str, summary_length: int) -> Tuple[str, bool]:
    summary_lines = filter(lambda x: not (x.startswith("#") or len(x) == 0), content.splitlines())
    summary_words = list(itertools.chain.from_iterable(map(lambda x: x.split(" "),summary_lines)))

    summary = ' '.join(summary_words[:min(len(summary_words), summary_length)])
    if len(summary) > summary_length:
        summary += "..."

    return (markdown_to_html(summary), len(summary) < summary_length)


def get_page_data(file_path: str) -> Tuple[dict, str]:
    meta = dict()
    meta["filename"] = os.path.basename(file_path)
    meta["filepath"] = file_path

    if not os.path.isfile(file_path):
        print(f"{PROG}: error: couldn't get page data file doesn't exists or is not a regular file: {file_path}", file=sys.stderr)
        exit(1)

    try:
        meta["frontmatter"] = json.loads(run(("frontmatter", "-f", "json", file_path), stdout=PIPE, check=True).stdout)
    except Exception as err:
        print(f"{PROG}: error: could not parse frontmatter: {file_path}: {err}", file=sys.stderr)
        exit(1)

    content = run(("frontmatter", "-c", file_path), encoding="utf-8", stdout=PIPE, check=True).stdout
    return (meta, content)


def single_command(args: argparse.Namespace) -> int:
    obj = include_files(args.include)
    obj["kind"] = "single"

    (meta, content) = get_page_data(args.input_file)
    obj = {**obj, **meta}

    try:
        obj["content"] = markdown_to_html(content)
    except Exception as err:
        print(f"{PROG}: error: could not convert file content to html: {args.input_file}: {err}", file=sys.stderr)
        exit(1)

    return run(
        [
            "stemp",
            "-f", "json",
            *list(itertools.chain.from_iterable(zip(["-i"]*len(args.includes), args.includes))),
            "-o", args.output if args.output else "/dev/fd/1",
            args.template,
            "-"
        ],
        encoding="utf-8",
        input=json.dumps(obj),
    ).returncode


def list_command(args: argparse.Namespace) -> int:
    obj = include_files(args.include)
    obj["pages"] = []
    obj["kind"] = "list"

    for f in args.files:
        (meta, content) = get_page_data(f)
        (summary, summary_is_content) = gen_summary(content, args.summary_length)
        obj["pages"].append({
            **meta,
            "summary": summary,
            "summary_is_content": summary_is_content,
        })

    return run(
        [
            "stemp",
            "-f", "json",
            *list(itertools.chain.from_iterable(zip(["-i"]*len(args.includes), args.includes))),
            "-o", args.output if args.output else "/dev/fd/1",
            args.template,
            "-"
        ],
        encoding="utf-8",
        input=json.dumps(obj),
    ).returncode


def main():
    args = parse_args()

    for dep in DEPS:
        if not which(dep):
            print(f"{PROG}: error: Could not find the required executable in path: {dep}", file=sys.stderr)
            print(f"{PROG}: info: For more information about required dependencies see --help.", file=sys.stderr)
            exit(1)

    if not os.path.isfile(args.template):
        print(f"{PROG}: error: template file doesn't exists or is not a regular file: {args.template}", file=sys.stderr)
        exit(1)

    match args.cmd:
        case "single":
            exit(single_command(args))
        case "list":
            exit(list_command(args))


if __name__ == "__main__":
    main()
